version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - 8080:8080
    command: -v start-dev --import-realm
    volumes:
      - ./keycloak-conf:/opt/keycloak/data/import
    depends_on:
      - keycloak-postgres
    networks:
      - mynetwork

  keycloak-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data_new_kubernetes:/var/lib/postgresql/data
    
    networks:
      - mynetwork

  mybackend:
    image: cprajwowski/backend
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - mynetwork

volumes:
  postgres_data_new_kubernetes:

networks:
  mynetwork:
    driver: bridge
