apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\PRA\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-postgres
  name: keycloak-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: keycloak-postgres
status:
  loadBalancer: {}
