kubectl apply -f namespace.yaml
kubectl apply -f postgres-deployment.yaml
kubectl apply -f postgres-service.yaml
kubectl apply -f postgres-pvc.yaml
kubectl apply -f keycloak-deployment.yaml
kubectl apply -f keycloak-service.yaml
kubectl apply -f keycloak-configmap.yaml
kubectl apply -f backend-deployment.yaml
kubectl apply -f backend-service.yaml
kubectl apply -f react-deployment.yaml
kubectl apply -f react-service.yaml
kubectl apply -f mongo-deployment.yaml
kubectl apply -f mongo-service.yaml